import type { Metadata } from "next";
import "./globals.css";
import Header from "./componenets/HEADER";
import Topheader from "./componenets/TOPHEADER";
import Footer from "./componenets/FOOTER";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en" className={montserrat.className}>
      <body>
<Topheader/>
        <Header/>
     
        {children}
        <Footer/>
      </body>
    </html>
  );
}